seed: 42

# slack_url: "https://hooks.slack.com/services/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"

dataset:
  name: SkinDataset
  params:
    flip: true
    verbose: true
  data_dir: ["data/images"]
  csv_filename: data/GroundTruth.csv 

transform:
  augment: RandAugment
  params:
    n: 3
    m: 12.0
  resize_to: [224, 224]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  name: EffNet
  params:
    backbone: tf_efficientnet_b6_ns
    pretrained: true
    pretrained_path: "pretrained"
    num_classes: 7
    dropout: 0.2
    multisample_dropout: true

find_lr: # this is its own mode 
  params:
    start_lr: 2.0e-6
    end_lr: 1
    num_iter: 500
    save_fig: true

train:
  batch_size: 16
  trainer: Trainer
  params:
    gradient_accumulation: 1
    num_epochs: 30
    steps_per_epoch: 0
    validate_interval: 1
    verbosity: 100
    amp: false

evaluation:
  batch_size: 16
  evaluator: Evaluator
  params:
    save_checkpoint_dir: checkpoint/efficientnetb6
    save_best: true
    prefix: effnet
    metrics: [skin_accuracy]
    valid_metric: skin_accuracy

loss:
  name: CrossEntropyLoss
  params:

optimizer:
  name: Adam
  params:
    lr: 1.0e-6
    weight_decay: 5.0e-4

scheduler:
  name: CustomLR

