seed: 42

# slack_url: "https://hooks.slack.com/services/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"

dataset:
  data_dir: ["data/images"]
  csv_filename: data/HAM10000_metadata.csv

transform:
  train:
    is_transformer: false
    transformer_name: NONE
    augment_opts:
    - name: "RandomHFlip"
      params:
        pvalue: 0.2
    - name: "Normalize"
      params:
        mean: [0.485, 0.456, 0.406]
        stdev: [0.229, 0.224, 0.225]
  valid:
    is_transformer: false
    augment_opts:
    - name: "Normalize"
      params:
        mean: [0.485, 0.456, 0.406]
        stdev: [0.229, 0.224, 0.225]

model:
  name: UNet
  params:
    backbone: resnet34_unet
    pretrained: true
    pretrained_path: "pretrained"
    num_classes: 23
    dropout: 0.2
    multisample_dropout: true

find_lr:
  start_lr: 1.0e-7
  end_lr: 1
  num_iter: 500
  save_fig: true

train:
  batch_size: 16
  trainer: Trainer
  params:
    gradient_accumulation: 1
    num_epochs: 300
    steps_per_epoch: 0
    validate_interval: 5
    verbosity: 1
    amp: false
    cuda: true

evaluation:
  batch_size: 1
  evaluator: Evaluator
  params:
    save_checkpoint_dir: checkpoint/baseline
    save_best: true
    prefix: effnet
    metrics: [dice_coefficient, jaccard_index]
    valid_metric: dice_coefficient
    mode: max
    improve_thresh: 1.0e-6

loss:
  name: DiceLoss
  params:

optimizer:
  name: Adam
  params:
    lr: 1.0e-4

scheduler:
  # name: CosineAnnealingWarmRestarts
  # name: StepLR
  # name: ReduceLROnPlateau
  # name: CosineAnnealingLR
  name: CustomLR
  params:
    final_lr: 1.0e-8

