seed: 42

slack_url: "https://hooks.slack.com/services/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"

dataset:
  name: MelDataset
  params:
    flip: true
    verbose: true
    square: true
    square_tta: 1
  inner_fold: 0
  outer_fold: 0
  outer_only: true
  data_dir: ["data"]
  csv_filename: data/GroundTruth.csv 


transform:
  augment: NONE
  params:
    # n: 3
    # m: 12.0
  # num_workers: 0
  # pad_ratio: null
  resize_to: [224, 224]
  # preprocess:
    # image_range: [0, 255]
    # input_range: [0, 1]
    # mean: [0.485, 0.456, 0.406]
    # sdev: [0.229, 0.224, 0.225]


model:
  name: UNet
  params:
    backbone: resnet34_unet
    pretrained: true
    pretrained_path: "pretrained"
    # num_classes: 23
    # dropout: 0.2
    # multisample_dropout: true


find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1
    num_iter: 500
    save_fig: true


train:
  batch_size: 16
  trainer: Trainer
  params:
    gradient_accumulation: 1
    num_epochs: 30
    steps_per_epoch: 0
    validate_interval: 1
    verbosity: 100
    amp: false
    cuda: true

evaluation:
  batch_size: 1
  evaluator: Evaluator
  params:
    save_checkpoint_dir: checkpoint/test
    save_best: true
    prefix: unet-resnet34
    metrics: [dice_coefficient, jaccard_index]
    valid_metric: dice_coefficient
    # mode: max
    # improve_thresh: 1.0e-6

loss:
  name: DiceLoss
  params:


optimizer:
  name: AdamW
  params:
    lr: 3.0e-4
    weight_decay: 5.0e-4


scheduler:
  name: CustomLR
  params:
    # final_lr: 1.0e-8
    # num_snapshots: 5


